### ISSUE TITLE
Uncaught SyntaxError

### ISSUE THREAD

**Issue by vincenzo** [openbibleinfo/Bible-Passage-Reference-Parser#11]
Hi. 

When I include any JS file other than `en_bcv_parser.min.js` (even with the non-minified English file), I get this error in the JS console: 

![screen shot 2015-01-28 at 07 54 59](https://cloud.githubusercontent.com/assets/76583/5934154/0fed9b6c-a6c3-11e4-8be2-d531c8c72538.png)

I am doing 

```html
<script src="js/it_bcv_parser.js"></script>
<script>
        var bcv = new bcv_parser;
        var b = bcv.parse("Numeri 23:19");
        alert(b.osis());
</script>
```

(and similar with other languages).

PS: thanks for opensourcing this, it's really useful.

**Comment by openbibleinfo** [comment]
It looks like the file isn't being interpreted as UTF-8. If you change your script tag to read:

`<script src="js/it_bcv_parser.js" charset="UTF-8"></script>`

Does that fix it?

I'm of two minds about including raw UTF-8 characters in the Javascript files--on one hand, it saves bandwidth, but on the other, it can lead to inconsistencies like this. Minifying the file, as you note, solves the problem by always using \uxxxx escaped characters.

**Comment by vincenzo** [comment]
@openbibleinfo Yeah, good call. That does fix it. So it's either that, or I'll just minify the JS file I need to use. I am guessing you are not thinking to include minified versions of all JS files? ;)

**Comment by openbibleinfo** [comment]
Since the minified files are derived directly from the js files, I wasn't planning on providing them for all the languages, no. Sorry. :)

**Comment by vincenzo** [comment]
No worries ;)
