### ISSUE TITLE
Plans to release as npm module?

### ISSUE THREAD

**Issue by bricejlin** [openbibleinfo/Bible-Passage-Reference-Parser#13]
Would love to be able to access over npm!

**Comment by openbibleinfo** [comment]
My hesitation with npm involves two separate but related issues: (1) All the "eu" scripts double the size of the download; and (2) All the different languages might make it confusing for someone to know which script to `require` in their project. Do you think I'm overthinking these problems?

**Comment by bricejlin** [comment]
What are the `eu` scripts for? You can put it in a .npmignore file so it won't get downloaded. And I'm sure people can figure it out, the readme is pretty clear

**Comment by sortofbusy** [comment]
Strong second on this; I've looked at Bible-parsing npm modules and none of them are as clear and well-documented as this one. Please consider it!

**Comment by openbibleinfo** [comment]
I'm tentatively planning on this in the November 2015 release.

**Comment by jamlen** [comment]
:+1: certainly for a node.js based application where I am not sending this to a browser, I am not that concerned about the package size.

**Comment by openbibleinfo** [comment]
I've published a first pass on npm here: https://www.npmjs.com/package/bible-passage-reference-parser

This is the first npm module I've created, so I'd appreciate any feedback before incorporating it into the Github repo in November.

To install:

```
npm install bible-passage-reference-parser
```

To run:

```javascript
var bcv_parser = require("bible-passage-reference-parser/js/en_bcv_parser").bcv_parser;
var bcv = new bcv_parser;
bcv.parse("matt6:2").osis(); // "Matt.6.2"
```

**Comment by sortofbusy** [comment]
Awesome! I'll be working with it in the next few days and will let you know how it goes.

**Comment by openbibleinfo** [comment]
Version 1.0.0 is now released on npm.
