### ISSUE TITLE
What are the default versification details of the apocrypha taken from?

### ISSUE THREAD

**Issue by curiousdannii** [openbibleinfo/Bible-Passage-Reference-Parser#22]
What are the default versification details taken from? Apparently there is a  version of the ESV with the apocrypha, but I haven't been able to find it online. Is it just the same as the NRSV? But that doesn't have EpJer...

**Comment by openbibleinfo** [comment]
You're right that the verse counts are from the NRSV, which does actually include EpJer as a separate book but, confusingly, continues the numbering from Baruch. See the footnote here for an explanation: https://www.biblegateway.com/passage/?search=Letter+of+Jeremiah+1:1&version=NRSV

**Comment by curiousdannii** [comment]
Thanks!
