### ISSUE TITLE
Q: How are the chapter lists generated?

### ISSUE THREAD

**Issue by curiousdannii** [openbibleinfo/Bible-Passage-Reference-Parser#23]
I would like my plugin to support more translations, and was wondering if you could say how you generated the [chapter lists](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser/blob/master/js/en_bcv_parser.js#L2336): is this data available somewhere already, or did you use a tool to generate them, or did you manually count (I hope not!)?

Second, I'm planning to add the translations (or hopefully in most cases, just aliases) to my plugin. Would you appreciate if I also submitted a pull request so they could be included in a future version of this package?

**Comment by openbibleinfo** [comment]
I mostly pulled them from Bible Gateway using a custom program. (It's not complicated--just walk through all the chapters and get the last verse number on each page.)

That would probably work; the May release will include correct verse totals for the Vulgate beyond the Psalms.

**Comment by curiousdannii** [comment]
Would you mind sharing the program (perhaps in a [Gist](https://gist.github.com/))?

**Comment by openbibleinfo** [comment]
Would you prefer just the output? I have a list of 608 chapters that vary in the number of verses, and which translations have which counts. Some of the counts on Bible Gateway are wrong, so I've been correcting them there; I'm not close to checking everything, though.

```
Wis.9	{"18":["it_cei","tl_mbbtag","en_ceb","en_cev","en_gnt","en_nabre","en_nrsv","en_nrsva","en_nrsvace","en_nrsvce","en_rsv","en_rsvce","en_rv1885","en_wyc","es_bjl","es_dhh","es_tla"],"19":["la_vulgate","en_dra"]}
```

It's a tab-separated file. The OSIS is in the first column, and then there's a JSON object with the number of verses as the key and an array of translations ("language" "_" "abbreviation") as the value.

**Comment by curiousdannii** [comment]
Yeah that would be great thanks!

There are some cases where the NAB had the same number of verses but it did have a different versification as the ESV, namely in the Psalms, when it had both a heading verse and joined two verses together. I'm intending to just check the Psalms manually for translations like the NJPS, but for other books that data should be enough to identify the issues.

**Comment by openbibleinfo** [comment]
I'll clean up the list and upload it for you; the data does include NJPS.

Here's all the work I've done so far, which includes Psalms: https://docs.google.com/spreadsheets/d/1z-BPF6Oh68crHp-S_keTiB2_UiY-H-Uotd4E_iPhFAg/edit?usp=sharing

I'm currently working through Sirach in the Vulgate, which is... involved.

**Comment by curiousdannii** [comment]
Just checking: you're still working on cleaning up the data? The google doc doesn't have the njps and looks like it's the same as https://gist.github.com/openbibleinfo/29fe7f73602e65a1ce16

**Comment by openbibleinfo** [comment]
Yes, here you are: https://gist.github.com/openbibleinfo/6dd946330aa6f86a1897e3f6fd10be52

**Comment by curiousdannii** [comment]
Excellent thanks!
