### ISSUE TITLE
How should additional translations in other languages be added?

### ISSUE THREAD

**Issue by curiousdannii** [openbibleinfo/Bible-Passage-Reference-Parser#24]
For my [reversify plugin](https://github.com/curiousdannii/reversify) I've started adding more English translations. But there is also [interest in adding translations in other languages](https://github.com/dev4christ/bibleapi/issues/7).

I'm not sure of the consequences of adding these translations. Could there be downsides to recognising unexpected translations, or are the abbreviations rare enough that this shouldn't prove to be a problem in practice?

I've thought about filtering the translations before adding them, but there's no way to know which language the parser has been built to support. Could you add a variable to the parser which would say the translation (en, fr, full etc)? This might be helpful even if we decide filtering the translations isn't needed.

**Comment by openbibleinfo** [comment]
For the purposes of the parser, I'm mostly interested in recognizing the major translations for each language; the main drawback to adding more is the risk of false positives. I believe I ran into one language where the translation abbreviation was also the name of a Bible book in that language, which caused problems.

Would you prefer that `bcv_parser.translation_info()` return a key that identifies the language of the requested translation, or would you prefer something like `bcv_parser.languages` to be an array of iso codes of the languages that the parser supports (e.g., derived from [here](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser/blob/master/src/ascii/data.txt#L17))?

**Comment by curiousdannii** [comment]
>  or would you prefer something like bcv_parser.languages to be an array of iso codes of the languages that the parser supports

This one please.

**Comment by openbibleinfo** [comment]
OK, this key will be available to you in the May 1 release. It's always an array; English looks like:

```javascript
bcv_parser.languages = ["en"];
```

I'm going to leave it undocumented for now in case we need to make changes.
