### ISSUE TITLE
Question about translation info

### ISSUE THREAD

**Issue by xdgimf** [openbibleinfo/Bible-Passage-Reference-Parser#25]
Does the book order returned by translation_info change?
for example a book with index of 99 in `translation_info()` might be different in `translation_info('niv')`

**Comment by openbibleinfo** [comment]
It can, yes. The NAB translation included in the English bundle, for example, has a different book order for the Old Testament: `default` places after Revelation the books Protestants consider to be Deuterocanonical, while `nab` intermixes them with Old Testament books.

**Comment by xdgimf** [comment]
Oh i see, Does the books also change? for example, a book in `default` translation might not be included in other translations

**Comment by openbibleinfo** [comment]
That's theoretically possible, and the parser can handle that case, but in practice none of the translations included in the parser do that.

**Comment by xdgimf** [comment]
I actually want to create a bible db that uses a pattern i found here https://github.com/scrollmapper/bible_databases, it uses a verse id system
Genesis 1:1 (Genesis chapter 1, verse 1) = 01001001 (01 001 001)

After I parse the passage, bcv will be converted to id
`{ b: 'Gen', c: 1, v: 1 } to 01001001`
Passage that contains multiple verse will be converted to array of ids
`[01001001, 01001002, 01001003]`

Anyway thanks for making this library open source, it really saves me time!

**Comment by openbibleinfo** [comment]
For those, I'd use the `default` book ids. 01-66 are definitely compatible with what they're doing there. I didn't see any books in the Apocrypha there, so you should be good.
