### ISSUE TITLE
is there any for Indonesian?

### ISSUE THREAD

**Issue by infacq** [openbibleinfo/Bible-Passage-Reference-Parser#28]

**Comment by openbibleinfo** [comment]
Not at the moment, sorry!

**Comment by alerque** [comment]
@infacq If you have good data as far as possible names for books it's not too hard to put together support a new language. If you are interested let us know what you have to start from.

**Comment by dominicsavb** [comment]
Hi,

What kind of data? I can supply you @alerque the data

**Comment by alerque** [comment]
@dominicsavb You'll want a comprehensive list of translations and the book names they use and their canonical abreviations, plus commonly used alternative names and abbreviations there are for each book. Knowing which translations use which versification scheme will help too. If you happen to know of any common pitfalls (such as the `1 The` snafu common in in English texts but easily a false-positive match for _First Thessalonians_) that will put you in good stead. Lastly you'll want some sample texts to match on to see how you're doing.

Armed with that data you can start putting it together in the right format to generate language support files from.
