### ISSUE TITLE
Trying to mix with Google Docs

### ISSUE THREAD

**Issue by wtanksleyjr** [openbibleinfo/Bible-Passage-Reference-Parser#29]
I'm experimenting with Javascript trying to slap this together into an Add-In for Google Docs (I'm currently picturing a quick sidebar to let me see which passages my document mentions, later I want to make something more powerful). But its Javascript doesn't _quite_ seem to work with the generated Coffeescript.

The problem is that there's no way to "import" or "require" a file; all of the things defined in the files are just made available to all the other files.

But, the generated Javascript doesn't seem to define anything, at least not explicitly. I don't know how to call it.

Has anyone here dealt with embedding this in a Google Script add-in before?

**Comment by curiousdannii** [comment]
In the browser loading en_bcv_parser.js would export bcv_parser onto the window object.

If you can't get that to work and you like CommonJS/node require() calls, then you could use browserify.
