### ISSUE TITLE
Parsing a larger text block with full and partial Bible references

### ISSUE THREAD

**Issue by renehamburger** [openbibleinfo/Bible-Passage-Reference-Parser#39]
The [.parse()](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser#parsestring-to-parse) works very well in returning all full Bible reference contained in a larger block of text. In contrast, [.parse_with_context()](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser#parse_with_contextstring-to-parse-string-context) for partial references is not able to find several partial references in a text block, but needs to be given the exact partial reference for parsing.

So there seems to be no out-of-the box way to the retrieve & parse the passages from a text like 'In Gen 3... But in verse 15...'. Or is there?

My current workaround is to use [.parse()](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser#parsestring-to-parse) to find & parse all complete references. And to then look for all numbers in the remaining text blocks and check them with [.parse_with_context()](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser#parse_with_contextstring-to-parse-string-context), both with and without a possible prefix like 'verse'.

Is anyone aware of an easier way to do this with this parser?

**Comment by chriswep** [comment]
with what solution did you end up @renehamburger ? Scratching my head on this one too. If you want to share any code you came up with, i'd appreciate!

**Comment by openbibleinfo** [comment]
Hi, this is what I use: https://gist.github.com/openbibleinfo/f0bb89d38cd8baa9298dbe97cfaa2251

It listens for a "q" and an optional "context" argument on port 3000. I use another language (such as PHP) to POST to this endpoint. The resulting text has <a> tags around ones found by the BCV parser and <maybe> tags found by the `handle_extra` function.

The HTTP part of this approach might be overkill for what you need.

**Comment by renehamburger** [comment]
Thanks for sharing this, @openbibleinfo!

[Here's my solution](https://github.com/renehamburger/blinx.js/blob/24eec37fb528d2840dacd44f66d1887d412d8f8e/src/blinx.class.ts#L364), which is largely independent of the language. I am basically looking for any numbers in the text and extend the selection to the front and back to pass it to the bcv instance. The text is the text in between two already recognised passages and the previous passage is used as the context for an partial references found in the text.

When it comes to finding references in html, [blinx.js](https://github.com/renehamburger/blinx.js) does a pretty good job!
