### ISSUE TITLE
Convert osis to Readable

### ISSUE THREAD

**Issue by centogram** [openbibleinfo/Bible-Passage-Reference-Parser#43]
Can you suggest a way to convert a stored osis string to a more user friendly readable format for a user to view?

**Comment by openbibleinfo** [comment]
Hello,

I suggest https://github.com/openbibleinfo/Bible-Reference-Formatter , which is designed for this purpose.

**Comment by centogram** [comment]
Thank you very much!  This is **exactly** what I was hoping to find.  Well done
