### ISSUE TITLE
The PHP version is available somewhere?

### ISSUE THREAD

**Issue by carmolim** [openbibleinfo/Bible-Passage-Reference-Parser#44]
Hello, loved the project, It will help me a lot. 

I was reading the read me and I saw that you developed a PHP version, the PHP version is available somewhere? Could you share it?

Thanks!

**Comment by alerque** [comment]
Having myself written something similar in PHP (and used it in production for years) I can suggest that this implementation is in another league from anything I've seen in PHP. You are almost certainly better off passing your data out to it (which you can do from PHP) and reading the results back in via JSON or similar. Porting the code to run natively would be a herculean effort.

If you describe your use case for precisely we might even be able to suggest something better.

**Comment by carmolim** [comment]
Thanks for your response.  Actually I've already done exactly what you suggested, I'm running the parser on a nodejs server and it's working perfectly. 

I would like to know if the php version is available to keep the entire implementation in the same language.

But maybe you can help me on my next step.  I will make some books available for reading online and I would like to automatically include a link in all biblical passages, so when the link is clicked would open a modal window with the text of the reference.

I have already done with php a much simpler program that finds the reference within the text and now I am using its parser to format and standardize the references found.

The next step would be to turn the parser output into a mysql query.  What would you approach to solve this problem?

**Comment by openbibleinfo** [comment]
Hi, the PHP code is available here (under "Available Source Code"): http://web.archive.org/web/20090227034152/http://www.gnpcb.org/esv/share/about/

While it's dead code, it's technically the property of my former employer.

**Comment by carmolim** [comment]
Thanks @openbibleinfo, the source code will help me to learn a little bit more.

**Comment by cco3** [comment]
I believe this can be closed
