### ISSUE TITLE
osis() for book without verses does not work.

### ISSUE THREAD

**Issue by cco3** [openbibleinfo/Bible-Passage-Reference-Parser#45]
`parser.parse('James').osis() === ''`

This is not what I would expect.

**Comment by alerque** [comment]
There is an option flag you need to pass to the parser when initializing it if you want to catch B references without C or V. If you were only parsing things that you expecting to _be_ references in the first place this default wouldn't make much sense, but it is optimized for finding BCV references in larger bodies of text. Matching bare book names consistently throws up too many false positives to be useful in that context.
