### ISSUE TITLE
PHP parser?

### ISSUE THREAD

**Issue by diegovogel** [openbibleinfo/Bible-Passage-Reference-Parser#48]
Hello, in the readme you mentioned a version of this written in PHP. Is there any chance it's open source? I'm working on a Bible app written in PHP. I was going to use this JS parser but something in PHP would be even better. Thanks.

**Comment by openbibleinfo** [comment]
Hello, please take a look at https://github.com/openbibleinfo/Bible-Passage-Reference-Parser/issues/44 ; you'll find a link to it near the bottom of the thread.

**Comment by diegovogel** [comment]
Thanks for the quick response!
